# Generated by Django 3.1 on 2020-08-30 05:37

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import storage.models.document
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('located', django_enumfield.db.fields.EnumField(enum=storage.models.document.DOCUMENT_LOCATION)),
                ('status', django_enumfield.db.fields.EnumField(enum=storage.models.document.DOCUMENT_STATUS)),
                ('uploaded_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('x', models.FloatField(null=True)),
                ('direction', django_enumfield.db.fields.EnumField(enum=storage.models.document.RESULT_DIRECTION)),
                ('doc_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.documentmodel')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='documentmodel',
            index=models.Index(fields=['status'], name='status_idx'),
        ),
        migrations.AddIndex(
            model_name='resultmodel',
            index=models.Index(fields=['direction'], name='direction_idx'),
        ),
        migrations.AddIndex(
            model_name='resultmodel',
            index=models.Index(fields=['doc_uuid'], name='doc_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='resultmodel',
            index=models.Index(fields=['direction', 'doc_uuid'], name='direction_uuid_idx'),
        ),
    ]
