# Generated by Django 3.1 on 2020-08-30 10:03

from django.db import migrations, models
import django_enumfield.db.fields
import storage.models.document


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=1, enum=storage.models.document.DOCUMENT_STATUS),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
